export const images = {
  FAVICON: "/favicon.png",
  CLOSE_ICON: {
    src: "/icons/close.svg",
    alt: "close",
    width: 20,
    height: 20,
  },
  SUCCESS: {
    src: "/images/success.svg",
    alt: "success",
    width: 158,
    height: 158,
  },
  ERROR: {
    src: "/images/error.svg",
    alt: "error",
    width: 158,
    height: 158,
  },
  AVATAR_PLACEHOLDER: {
    src: "/images/profile-placeholder.svg",
    alt: "avatar",
    small: 51,
    authorSize: 60,
    medium: 96,
    large: 120,
  },
  LOGO: {
    src: "/images/logo-placeholder.svg",
    alt: "logo",
    footerWidth: 276,
    footerHeight: 30,
    headerWidth: 237,
    headerHeight: 40,
    headerMobileWidth: 142,
  },
  PROFILE_ICON: {
    src: "/icons/profile.svg",
    alt: "profile",
    width: 26,
    height: 26,
  },
  BRAND_ICON: {
    src: "/images/brand-icon.png",
    alt: "icon",
    width: 24,
    height: 8,
  },
  WALLET_CONTRACT_1_50: {
    src: "/images/contract_1-50.jpg",
    alt: "token_1_50",
    width: 125,
    height: 125,
  },
  WALLET_CONTRACT_51_100: {
    src: "/images/contract_51-100.jpg",
    alt: "token_51_100",
    width: 125,
    height: 125,
  },
};
